FROM alpine:latest
# RUN yum install nmap-ncat --disablerepo=* --enablerepo=rhel-7-server-rpms -y && yum clean all -y
# RUN yum install telnet --disablerepo=* --enablerepo=rhel-7-server-rpms -y && yum clean all -y
# RUN yum install net-tools --disablerepo=* --enablerepo=rhel-7-server-rpms -y && yum clean all -y
# RUN yum install bind-utils --disablerepo=* --enablerepo=rhel-7-server-rpms -y && yum clean all -y
# RUN yum install mod_ssl --disablerepo=* --enablerepo=rhel-7-server-rpms -y && yum clean all -y
CMD ["/bin/sh"]
